def get_keymates(key_input, layout="QWERTY_en_US"):

    # TODO : remove this override
    layout = "AZERTY_fr"

    gui_keymates_en_us = {
        'GRAVE': '`',
        'SPACE': 'Space',
        'MINUS': '-',
        'EQUAL': '=',
        'BACKSPACE': 'Backspace',
        'LEFTBRACE': '[',
        'RIGHTBRACE': ']',
        'BACKSLASH': '\\',
        'TAB': 'Tab',
        'CAPS_LOCK': 'CapsLock',
        'LEFTSHIFT': 'Shift',
        'RIGHTSHIFT': 'Shift',
        'LEFTCTRL': 'Ctrl',
        'RIGHTCTRL': 'Ctrl',
        'LEFTALT': 'Alt',
        'RIGHTALT': 'Alt',
        'APOSTROPHE': "'",
        'SEMICOLON': ';',
        'SLASH': '/',
        'DOT': '.',
        'COMMA': ',',
        'PAGEUP': 'PgUp',
        'PAGEDOWN': 'PgDn',
        'MENU': 'Menu',
        'HOME': 'Home',
        'END': 'End',
        'DELETE': 'Del',
        'ESC': 'Esc',
        'FN': 'Fn',
        'LEFTMETA': 'Super',
        'RIGHTMETA': 'Super',
        'ENTER': 'Enter',
        'UP': '↑',
        'DOWN': '↓',
        'LEFT': '←',
        'RIGHT': '→',
        'INSERT': 'Ins',
        'NUMLOCK': 'Num',
        'KPPLUS': 'KP+',
        'KPMINUS': 'KP-',
        'KPDOT': 'KP.',
        'KPSLASH' : 'KP/',
        'KPASTERISK' : 'KP*',
        'KPENTER': 'KPEnter',
        'SCROLLLOCK': 'ScrLk',
        }

    db_keymates_en_us = {
        'asciitilde': 'GRAVE',
        'exclam': '1',
        'at': '2',
        'numbersign': '3',
        'dollar': '4',
        'percent': '5',
        'asciicircum': '6',
        'ampersand': '7',
        'asterisk': '8',
        'parenleft': '9',
        'parenright': '0',
        'KP_1': 'KP1',
        'KP_2': 'KP2',
        'KP_3': 'KP3',
        'KP_4': 'KP4',
        'KP_5': 'KP5',
        'KP_Begin': 'KP5',
        'KP_6': 'KP6',
        'KP_7': 'KP7',
        'KP_8': 'KP8',
        'KP_9': 'KP9',
        'KP_0': 'KP0',
        'underscore': 'MINUS',
        'plus': 'EQUAL',
        'braceleft': 'LEFTBRACE',
        'bracketleft': 'LEFTBRACE',
        'braceright': 'RIGHTBRACE',
        'bracketright': 'RIGHTBRACE',
        'bar': 'BACKSLASH',
        'colon': 'SEMICOLON',
        'quotedbl': 'APOSTROPHE',
        'less': 'COMMA',
        'greater': 'DOT',
        'period': 'DOT',
        'question': 'SLASH',
        'Prior': 'PAGEUP',
        'Next': 'PAGEDOWN',
        'Control_L': 'LEFTCTRL',
        'Control_R': 'RIGHTCTRL',
        'Shift_L': 'LEFTSHIFT',
        'Shift_R': 'RIGHTSHIFT',
        'Alt_L': 'LEFTALT',
        'Alt_R': 'RIGHTALT',
        'Return': 'ENTER',
        'Super_L': 'LEFTMETA',
        'Super_R': 'RIGHTMETA',
        'Escape': 'ESC',
        'XF86WakeUp': 'FN',
        'Insert': 'INSERT',
        'Num_Lock': 'NUMLOCK',
        'KP_Add': 'KPPLUS',
        'KP_Subtract': 'KPMINUS',
        'KP_Decimal' : 'KPDOT',
        'KP_Enter' : 'KPENTER',
        'KP_Divide'   : 'KPSLASH',
        'KP_Multiply' : 'KPASTERISK',
        'KP_Delete'   : 'DELETE',
        'KP_Insert'   : 'INSERT',
        'KP_Home'     : 'HOME',
        'KP_Up'       : 'UP',
        'KP_Prior'    : 'PAGEUP',
        'KP_Right'    : 'RIGHT',
        'KP_Left'     : 'LEFT',
        'KP_End'      : 'END',
        'KP_Down'     : 'DOWN',
        'KP_Next'     : 'PAGEDOWN',
        'Scroll_Lock': 'SCROLLLOCK',
        }

    gui_keymates_AZERTY_fr = {
        'SCROLLLOCK': 'ScrLk',

        'NUMLOCK': 'Num',
        'GRAVE': '²',
        'EQUAL': '=',
        'MINUS': ')',
        'M': ',',
        'DOT': ';',
        'SLASH': '!',
        'COMMA': ';',

        'BACKSPACE': 'Backspace',
        'TAB': 'Tab',
        'CAPS_LOCK': 'CapsLock',
        'LEFTSHIFT': 'Shift',
        'RIGHTSHIFT': 'Shift',
        'LEFTCTRL': 'Ctrl',
        'RIGHTCTRL': 'Ctrl',
        'LEFTALT': 'Alt',
        'RIGHTALT': 'AltGr',
        'RIGHTBRACE': '€',
        'INSERT': 'Ins',
        'PAGEUP': 'PgUp',
        'PAGEDOWN': 'PgDn',
        'HOME': 'Home',
        'END': 'End',
        'DELETE': 'Del',
        'ESC': 'Esc',
        'LEFTMETA': 'Super',
        'RIGHTMETA': 'Super',
        'ENTER': 'Enter',
        'SPACE' : 'Space',
        'UP': '↑',
        'DOWN': '↓',
        'LEFT': '←',
        'RIGHT': '→',
        'FN': 'Fn',
        'MENU': 'Menu',
        'Q': 'A',
        'W': 'Z',
        'APOSTROPHE': 'Ù',
        'LEFTBRACE': '^',
        'A': 'Q',
        'Z': 'W',
        'DOT': ':',
        'BACKSLASH': "*",
        'ESC': 'Esc',
        'FN': 'Fn',
        'KPPLUS': 'KP+',
        'KPMINUS': 'KP-',
        'KPDOT': 'KP.',
        'SCROLLLOCK': 'ScrLk',
        'KPSLASH' : 'KP/',
        'KPASTERISK' : 'KP*',
        'KPENTER': 'KPEnter',
    }

    db_keymates_AZERTY_fr = {
        'twosuperior': 'GRAVE',
        'ampersand': '1',
        'eacute': '2',
        'Eacute': '2',
        'quotedbl': '3',
        'apostrophe': '4',
        'parenleft': '5',
        'minus': '6',
        'egrave': '7',
        'Egrave': '7',
        'underscore': '8',
        'ccedilla': '9',
        'Ccedilla': '9',
        'agrave': '0',
        'Agrave': '0',
        'KP_1': 'KP1',
        'KP_2': 'KP2',
        'KP_3': 'KP3',
        'KP_4': 'KP4',
        'KP_5': 'KP5',
        'KP_Begin': 'KP5',
        'KP_6': 'KP6',
        'KP_7': 'KP7',
        'KP_8': 'KP8',
        'KP_9': 'KP9',
        'KP_0': 'KP0',
        'parenright': "MINUS",
        'degree': 'MINUS',
        'plus' : 'equal',
        'comma': 'M',
        'semicolon': 'COMMA',
        'colon': "DOT",
        'exclam': 'SLASH',
        'Shift_R': 'RIGHTSHIFT',
        'Shift_L': 'LEFTSHIFT',
        'dollar': 'RIGHTBRACE',
        'sterling': 'RIGHTBRACE',
        'asciicircum': 'LEFTBRACE',
        'a': 'Q',
        'z': 'W',
        'Control_L': 'LEFTCTRL',
        'Control_R': 'RIGHTCTRL',
        'Prior': 'PAGEUP',
        'Next': 'PAGEDOWN',
        'Return': 'ENTER',
        'asterisk': 'BACKSLASH',
        'mu': 'BACKSLASH',
        'Escape' : 'ESC',
        'Super_L': 'LEFTMETA',
        'Super_R': 'RIGHTMETA',
        'Alt_L': 'LEFTALT',
        'Alt_R': 'RIGHTALT',
        'ugrave' : 'APOSTROPHE',
        'percent' : 'APOSTROPHE',
        'q': 'A',
        'w': 'Z',
        'colon': 'DOT',
        'question': 'M',
        'period': 'COMMA',
        'slash': 'DOT',
        'section': 'SLASH',
        'ISO_Level3_Shift': 'RIGHTALT',
        'Num_Lock': 'NUMLOCK',
        'KP_Add': 'KPPLUS',
        'KP_Subtract': 'KPMINUS',
        'KP_Decimal' : 'KPDOT',
        'KP_Enter' : 'KPENTER',
        'KP_Divide'   : 'KPSLASH',
        'KP_Multiply' : 'KPASTERISK',
        'KP_Delete'   : 'DELETE',
        'KP_Insert'   : 'INSERT',
        'KP_Home'     : 'HOME',
        'KP_Up'       : 'UP',
        'KP_Prior'    : 'PAGEUP',
        'KP_Right'    : 'RIGHT',
        'KP_Left'     : 'LEFT',
        'KP_End'      : 'END',
        'KP_Down'     : 'DOWN',
        'KP_Next'     : 'PAGEDOWN',
        'Scroll_Lock': 'SCROLLLOCK',
    }

    db_keymates = {
        "QWERTY_en_US": db_keymates_en_us,
        "AZERTY_fr": db_keymates_AZERTY_fr
    }

    gui_keymates = {
        "QWERTY_en_US": gui_keymates_en_us,
        "AZERTY_fr": gui_keymates_AZERTY_fr
    }



    try:
        db_keymate = db_keymates[layout][key_input]
    except KeyError:
        db_keymate = key_input.upper()

    try:
        gui_keymate = gui_keymates[layout][db_keymate]
    except KeyError:
        gui_keymate = db_keymate

    return f"KEY_{db_keymate}", gui_keymate

